#!/usr/bin/env bash
# https://cirosantilli.com/linux-kernel-module-cheat#bisection
set -eu
git submodule update --recursive
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
"${root_dir}/build-qemu" --arch aarch64 --qemu-build-id bisect
"${root_dir}/run" --arch aarch64 --qemu-build-id bisect --quit-after-boot
