#!/usr/bin/env python3
import common
parser = self.get_argparse(
    argparse_args={'description':'Convert a BST vs heap stat file into a gnuplot input'}
)
args = self.setup(parser)
stats = self.get_stats()
it = iter(stats)
i = 1
for stat in it:
    try:
        next_stat = next(it)
    except StopIteration:
        # Automatic dumpstats at end may lead to odd number of stats.
        break
    print('{} {} {}'.format(i, stat, next_stat))
    i += 1
