#!/usr/bin/env bash
set -eu
test_size=1
while [ $# -gt 0 ]; do
  case "$1" in
    --size)
      test_size="$2"
      shift 2
      ;;
  esac
done
./build --all-archs qemu-gem5-buildroot
if [ "$test_size" -ge 3 ]; then
  ./build --arch aarch64 all-linux
fi
