#!/usr/bin/env python3

import imp
import os
import subprocess

git_root = subprocess.check_output([
    'git',
    'rev-parse',
    '--show-toplevel',
]).decode().rstrip()
build_userland = imp.load_source(
    'build_userland',
    os.path.join(git_root, 'build-userland')
)

class Main(build_userland.Main):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults={
                'gcc_which': 'host',
                'in_tree': True,
                'targets': ['.'],
            }
        )

if __name__ == '__main__':
    Main().cli()
