= build usage

....
./build [OPTIONS] [-- EXTRA_MAKE_ARGS]
....

[options="header"]
|===
|Name |Argument name        | Description
|`-a` |`ARCH`               | Build for architecture `ARCH`.
|`-b` |`BR2_FILE`           | Also use the given Buildroot configuration fragment file.
                              Pass multiple times to use multiple fragment files.
|`-B` |`BR2_CONFIG`         | Add a single Buildroot option to the current build.
                              Example: `-B 'BR2_TARGET_ROOTFS_EXT2_SIZE="500M"'`
|`-c` |`BR2_FILE`           | Also use the given Buildroot configuration fragment file.
                              Pass multiple times to use multiple fragment files.
|`-C` |                     | Skip the Buildroot configuration. Saves a few seconds, but requires
                              you to know what you are doing :-)
|`-g` |                     | Enable gem5 build. You also need to use `-- gem5-reconfigure`
                              to rebuild gem5 after the initial build.
|`-h` |                     | Show this help message.
|`-I` |                     | Enable initramfs for the current build.
|`-i` |                     | Enable initrd for the current build.
|`-K` |`KERNEL_CONFIG_FILE` | Use `KERNEL_CONFIG_FILE` as the exact Linux
                              kernel configuration. Ignore the default `kernel_config_fragment`.
                              You also need to `touch KERNEL_CONFIG_FILE` if that file is
                              older than the latest build.
|`-k` |                     | Reconfigure and rebuild the kernel module package.
                              Shortcut for `-- kernel_module-reconfigure`.
|`-l` |                     | Reconfigure and rebuild the linux kernel.
                              Shortcut for `-- linux-reconfigure`.
|`-p` |                     | Pass extra arguments to the `rootfs_post_build_script`.
|`-q` |                     | Reconfigure and rebuild QEMU.
                              Shortcut for `-- host-qemu-reconfigure`.
|`-S` |                     | Don't build QEMU with SDL support.
                              Graphics such as X11 won't work, only the terminal.
|`-v` |                     | Do a verbose build.
|===
