#!/usr/bin/env bash
set -eu
test_size=1
while [ $# -gt 0 ]; do
  case "$1" in
    --size)
      test_size="$2"
      shift 2
      ;;
  esac
done
./build-bench-boot --size "$test_size"
./build --all-archs test-gdb
