#!/usr/bin/env bash
set -eu
archs='x86_64 arm aarch64'
gem5=true
while getopts A:G OPT; do
  case "$OPT" in
    A)
      archs="$OPTARG"
      ;;
    G)
      gem5=false
      ;;
  esac
done
shift "$(($OPTIND - 1))"
for arch in $archs; do
  ./build-qemu --arch "$arch"
  ./build --arch "$arch" --kernel-modules -l "$@"
  if "$gem5"; then
    ./build-gem5 --arch "$arch"
  fi
done
