#!/usr/bin/env python3

import os
import subprocess

import common

build_userland = common.import_path_relative_root('build-userland')

class Main(build_userland.Main):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults={
                'gcc_which': 'host',
                'in_tree': True,
                'targets': ['.'],
            }
        )

if __name__ == '__main__':
    Main().cli()
