#!/usr/bin/env python3

import distutils.dir_util
import os
import shutil

import common
from shell_helpers import LF

class Main(common.BuildCliFunction):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#rootfs_overlay
''')
    def build(self):
        # TODO: print rsync equivalent, move into shell_helpers.
        distutils.dir_util.copy_tree(
            self.env['rootfs_overlay_dir'],
            self.env['out_rootfs_overlay_dir'],
            update=1,
        )

if __name__ == '__main__':
    Main().cli()
