#!/usr/bin/env python3

import distutils.dir_util
import os
import shutil

import common

class CopyOverlayComponent(common.BuildComponent):
    def do_build(self, args):
        distutils.dir_util.copy_tree(
            common.rootfs_overlay_dir,
            common.out_rootfs_overlay_dir,
            update=1,
        )

    def get_argparse_args(self):
        return {
            'description': '''\
Copy our git tracked rootfs_overlay to the final generated rootfs_overlay
that also contains generated build outputs. This has the following advantages
over just adding that to BR2_ROOTFS_OVERLAY:
- also works for non Buildroot root filesystesms
- places everything in one place for a nice 9P mount
''',
        }

if __name__ == '__main__':
    CopyOverlayComponent().main()
