#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
common_setup
./build-all
./zip-img
tag="sha-${common_sha}"
upload_basename="images-${common_sha}.zip"
git tag "$tag"
git push --tags
#curl "https://api.github.com/repos/cirosantilli/linux-kernel-module-cheat/releases/tags/${tag}/assets?access_token=$(cat data/access_token)&tag_name=${upload_basename}" \
#  --header 'Content-Type: application/zip' \
#  --upload-file "${common_out_dir}/${upload_basename}" \
#  -H 'Accept: application/vnd.github.v3+json' \
#  -X POST \
#;
./bench-all -Au
