#!/usr/bin/env bash
gem5_out_dir="$(pwd)/out/common/gem5"
buildroot_out_dir="$(pwd)/out/aarch64/buildroot"
M5_PATH="${gem5_out_dir}/system" \
  "${gem5_out_dir}/build/ARM/gem5.opt" \
  ./gem5/gem5/configs/example/arm/fs_bigLITTLE.py \
  --big-cpus=2 \
  --caches \
  --disk="${buildroot_out_dir}/images/rootfs.ext2" \
  --dtb "${gem5_out_dir}/system/arm/dt/armv8_gem5_v1_big_little_2_2.dtb" \
  --kernel="${buildroot_out_dir}/build/linux-custom/vmlinux" \
  --little-cpus=2 \
;
