#!/usr/bin/env bash
M5_PATH="$(pwd)/out/aarch64/buildroot/build/gem5-1.0/system" \
  ./out/aarch64/buildroot/build/gem5-1.0/gem5/build/ARM/gem5.opt \
  ./out/aarch64/buildroot/build/gem5-1.0/gem5/configs/example/arm/fs_bigLITTLE.py \
  --disk="$(pwd)/out/aarch64/buildroot/images/rootfs.ext2" \
  --kernel="$(pwd)/out/aarch64/buildroot/build/linux-custom/vmlinux" \
  --big-cpus=2 \
  --little-cpus=2 \
  --caches \
  --dtb "$(pwd)/out/aarch64/buildroot/build/gem5-1.0/gem5/system/arm/dt/armv8_gem5_v1_big_little_2_2.dtb" \
;
