#!/usr/bin/env bash
. common
set_common_vars -L "${common_linux_variant}" -M "${common_gem5_variant}" aarch64 true
M5_PATH="${common_gem5_system_dir}" \
  "${common_gem5_build_dir}/ARM/gem5.opt" \
  "${common_gem5_default_src_dir}/configs/example/arm/fs_bigLITTLE.py" \
  --big-cpus=2 \
  --caches \
  --disk="${common_images_dir}/rootfs.ext2" \
  --dtb "${common_gem5_system_dir}/arm/dt/armv8_gem5_v1_big_little_2_2.dtb" \
  --kernel="${common_vmlinux}" \
  --little-cpus=2 \
;
