#!/usr/bin/env python3

import sys

import common
from shell_helpers import LF

parser = self.get_argparse(
    default_args={'gem5':True},
    argparse_args={'description':'Connect a terminal to a running gem5 instance'}
)
args = self.setup(parser)
sys.exit(self.sh.run_cmd([
    kwargs['gem5_m5term'], LF,
    'localhost', LF,
    str(kwargs['gem5_telnet_port']), LF,
]))
