#!/usr/bin/env bash
. common
while getopts n: OPT; do
  case "$OPT" in
    n)
      common_run_id="$OPTARG"
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
set_common_vars -n "$common_run_id" "$arch" true
telnet localhost "$common_gem5_telnet_port"
