#!/usr/bin/env python3
import re
import common
parser = common.get_argparse(
    argparse_args={'description':'Get the value of a gem5 stat from the stats.txt file.'}
)
parser.add_argument(
  'stat',
  default='^system.cpu[0-9]*.numCycles$',
  help='Python regexp matching the full stat name of interest',
  nargs='?',
)
args = common.setup(parser)
stat_re = re.compile(args.stat)
with open(common.stats_file, 'r') as statfile:
    for line in statfile:
        if line[0] != '-':
            cols = line.split()
            if len(cols) > 1 and stat_re.search(cols[0]):
                print(cols[1])
