#!/usr/bin/env python3

import sys

import common

parser = common.get_argparse(
    default_args={'gem5':True},
    argparse_args={'description':'Connect a terminal to a running gem5 instance'}
)
args = common.setup(parser)
sys.exit(common.run_cmd([
    common.gem5_m5term, common.Newline,
    'localhost', common.Newline,
    str(common.gem5_telnet_port), common.Newline,
]))
