#!/usr/bin/env python3
import common
parser = self.get_argparse(
    argparse_args={'description':'Get the value of a gem5 stat from the stats.txt file.'}
)
parser.add_argument(
    'stat',
    default=None,
    help='Python regexp matching the full stat name of interest',
    nargs='?',
)
args = self.setup(parser)
stats = self.get_stats(kwargs['stat'])
print('\n'.join(stats))
