#!/usr/bin/env python3

import types

import common
from shell_helpers import LF

class Main(common.LkmcCliFunction):
    def __init__(self):
        super().__init__(
            description='''\
Print the value of a self.env['py'] variable.

This is useful to:

* give dry commands on the README that don't change when we refactor directory structure
* create simple bash scripts that call use self.env['py'] variables

For example, to get the Buildroot output directory for an ARM build, use:

....
./%(prog)s -a arm buildroot_build_dir
....

List all available variables:

....
./%(prog)s
....
''',
            do_print_time=False,
        )
        self.add_argument('variable', nargs='?')

    def timed_main(self):
        variable = self.env['variable']
        if variable:
            print(self.env[variable])
        else:
            for key in self.env:
                print('{}={}'.format(key, self.env[key]))

if __name__ == '__main__':
    Main().cli()
