#!/usr/bin/env bash
# https://cirosantilli.com/linux-kernel-module-cheat#github-pages
set -eu
git push
./build-doc --github-pages
git branch -D gh-pages
git checkout --orphan gh-pages
git reset
cp out/README.html index.html
git add _config.yml index.html
git commit --message "$(git log -n1 --pretty='%H' master)"
git push --force
git symbolic-ref HEAD refs/heads/master
git reset
rm index.html
