#!/usr/bin/env bash
# We could also use Ctrl + Alt + 2 on the SDL GUI,
# but that opens up a tiny window which can't scroll up or be searched.
# And this is the only way when running in -noscreen.
telnet localhost 45454
