#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
parsed=$(getopt -o "${common_getopt_flags}" -l "$common_getopt_flags_long" -- "$@")
eval set -- "$parsed"
while true; do
  case "$1" in
    *)
      common_getopt_case "$@"
      ;;
  esac
done
common_setup
./qemu/scripts/simpletrace.py \
  "${common_build_dir}/host-qemu-custom/trace-events-all" \
  "${common_qemu_run_dir}/trace.bin" \
> "${common_trace_txt_file}"
