#!/usr/bin/env bash
set -eu
. common
set -- ${cli_qemu_trace2txt:-} "$@"
while getopts a: OPT; do
  case "$OPT" in
    a)
      arch="$OPTARG"
      ;;
  esac
done
set_common_vars "$arch" false
./qemu/scripts/simpletrace.py \
  "${build_dir}/host-qemu-custom/trace-events-all" \
  "${qemu_out_dir}/trace.bin" \
> "${common_trace_txt_file}"
