#!/usr/bin/env python3

'''
https://github.com/cirosantilli/linux-kernel-module-cheat#release-zip
'''

import os
import subprocess
import zipfile

import common

def main():
    os.makedirs(common.release_dir, exist_ok=True)
    if os.path.exists(common.release_zip_file):
        os.unlink(common.release_zip_file)
    zipf = zipfile.ZipFile(common.release_zip_file, 'w', zipfile.ZIP_DEFLATED)
    for arch in common.arches:
        common.setup(common.get_argparse(default_args={'arch': arch}))
        zipf.write(common.qcow2_file, arcname=os.path.relpath(common.qcow2_file, common.root_dir))
        zipf.write(common.linux_image, arcname=os.path.relpath(common.linux_image, common.root_dir))
    zipf.close()

if __name__ == '__main__':
    main()
