#!/usr/bin/env python3

'''
Usage: https://github.com/cirosantilli/linux-kernel-module-cheat#prebuilt

Implementation:
https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo/50540591#50540591
'''

import urllib.request

import common

_json = common.github_make_request(path='/releases')
asset = _json[0]['assets'][0]
urllib.request.urlretrieve(asset['browser_download_url'], asset['name'])
