#!/usr/bin/env python3

import common
from shell_helpers import LF

class Main(common.LkmcCliFunction):
    def __init__(self):
        super().__init__(
            description='''\
Usage: https://github.com/cirosantilli/linux-kernel-module-cheat#prebuilt

Implementation:
https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo/50540591#50540591
''',
        )

    def timed_main(self):
        self.log_info('Downloading the release, this may take several seconds / a few minutes.')
        _json = self.github_make_request(path='/releases')
        asset = _json[0]['assets'][0]
        self.sh.wget(asset['browser_download_url'], asset['name'])

if __name__ == '__main__':
    Main().cli()
