#!/usr/bin/env bash
# This is run as part of:
#      make target-finalize
# which gets called by the default target.
# To test it out, arguments can be passed with:
#     make BR2_ROOTFS_POST_SCRIPT_ARGS="asdf qwer"
target_dir="$1"
mkdir -p \
  "${target_dir}/mnt/9p" \
  "${target_dir}/mnt/out" \
;
