#!/usr/bin/env bash
# This is run as part of:
#      make target-finalize
# which gets called by the default target.
target_dir="$1"
# /dev/* entries were taken out of BusyBox inittab,
# no need to do that on every boot, right?
mkdir -p \
  "${target_dir}/mnt/9p/data" \
  "${target_dir}/mnt/9p/out" \
  "${target_dir}/mnt/9p/out_rootfs_overlay" \
  "${target_dir}/mnt/9p/rootfs_overlay" \
  "${target_dir}/mnt/overlay" \
  "${target_dir}/mnt/work" \
  "${target_dir}/mnt/upper" \
  "${target_dir}/dev/pts" \
  "${target_dir}/dev/shm" \
;
# Maybe there is a cleaner way to get rid of those files,
# like disabling some Buildroot packages, but no patience.
#
# As of 2d5f95b1839986ca6d7b568296374a2403d2693d
# xorg must be removed or else we get a black screen:
# https://bugs.busybox.net/show_bug.cgi?id=11066
init_d="${target_dir}/etc/init.d"
rm -rf \
  "${init_d}/S01logging" \
  "${init_d}/S01syslogd" \
  "${init_d}/S02klogd" \
  "${init_d}/S02sysctl" \
  "${init_d}/S20urandom" \
  "${init_d}/S40network" \
  "${init_d}/S40xorg" \
  "${init_d}/S50sshd" \
;
