#!/usr/bin/env bash
# This is run as part of:
#      make target-finalize
# which gets called by the default target.
# To test it out, arguments can be passed with:
#     make BR2_ROOTFS_POST_SCRIPT_ARGS="asdf qwer"
target_dir="$1"
mkdir -p \
  "${target_dir}/mnt/9p" \
  "${target_dir}/mnt/out" \
;
# Maybe there is a cleaner way to get rid of those files,
# like disabling some Buildroot packages, but no patience.
rm -rf \
  "${target_dir}/etc/init.d/S01logging" \
  "${target_dir}/etc/init.d/S20urandom" \
  "${target_dir}/etc/init.d/S40network" \
;
