#!/usr/bin/env bash
images_dir="$1"
cd "$images_dir"
f=rootfs.ext2
exe="${HOST_DIR}/bin/qemu-img"
if [ -f "$exe" ] && [ -f "$f" ]; then
  # TODO why does qemu-img produce traces?
  # http://lists.nongnu.org/archive/html/qemu-discuss/2018-04/msg00019.html
  "$exe" -T "pr_manager_run,file=/dev/null" convert -f raw -O qcow2 "$f" "${f}.qcow2"
fi
