#!/usr/bin/env bash
# This is run as part of:
#      make target-finalize
# which gets called by the default target.
# To test it out, arguments can be passed with:
#     make BR2_ROOTFS_POST_SCRIPT_ARGS="asdf qwer"
target_dir="$1"
shift
net=true
while getopts 'n' OPT; do
  case "$OPT" in
    n)
      net=false
    ;;
  esac
done
shift $(($OPTIND - 1))
if ! "$net"; then
  rm -f "${target_dir}/etc/init.d/"S*network
fi
