#!/usr/bin/env bash
# This is run as part of:
#      make target-finalize
# which gets called by the default target.
target_dir="$1"
mkdir -p \
  "${target_dir}/mnt/9p" \
  "${target_dir}/mnt/out" \
;
# Maybe there is a cleaner way to get rid of those files,
# like disabling some Buildroot packages, but no patience.
#
# As of 2d5f95b1839986ca6d7b568296374a2403d2693d
# xorg must be removed or else we get a black screen:
# https://bugs.busybox.net/show_bug.cgi?id=11066
rm -rf \
  "${target_dir}/etc/init.d/S01logging" \
  "${target_dir}/etc/init.d/S20urandom" \
  "${target_dir}/etc/init.d/S40network" \
  "${target_dir}/etc/init.d/S40xorg" \
  "${target_dir}/etc/init.d/S50sshd" \
;
