#!/usr/bin/env python3

import common

parser = common.get_argparse(
    default_args={'gem5':True},
    argparse_args={'description':'Run executable in gem5 se.py syscall emulation mode'}
)
parser.add_argument(
    'executable',
)
args = common.setup(parser)
common.run_cmd([common.executable, common.gem5_se_file, '-c', args.executable])
