#!/usr/bin/env bash
if [ "$#" -gt 0 ]; then
  brk="-ex 'break $1'"
else
  brk=""
fi
cd buildroot/output/build/linux-*.*.*/
cmd="gdb \
  -ex 'add-auto-load-safe-path $(pwd)' \
  -ex 'file vmlinux' \
  -ex 'set arch i386:x86-64:intel' \
  -ex 'target remote localhost:1234' \
  $brk \
  -ex 'continue' \
  -ex 'disconnect' \
  -ex 'set arch i386:x86-64' \
  -ex 'target remote localhost:1234'
"
echo "$cmd"
eval "$cmd"
