#!/usr/bin/env bash
set -eu
. common
set -- ${cli_rungdbserver:-} "$@"
arch='x86_64'
gem5=false
while getopts a:g OPT; do
  case "$OPT" in
    a)
      arch="$OPTARG"
      ;;
    g)
      gem5=true
      ;;
  esac
done
shift "$(($OPTIND - 1))"
executable="$1"
set_common_vars "$arch" "$gem5"
"${host_dir}/usr/bin/${arch}-linux-gdb" \
  -q \
  -ex "set sysroot ${buildroot_out_dir}/staging" \
  -ex 'target remote localhost:45455' \
  -ex 'tb main' \
  -ex 'c' \
  "${build_dir}/${executable}" \
;
