#!/usr/bin/env bash
outdir="$(pwd)/buildroot/output.arm-gem5~"
M5_PATH="$(pwd)/gem5-system" \
./gem5/build/ARM/gem5.opt \
  gem5/configs/example/fs.py \
  --disk-image="${outdir}/images/rootfs.ext2" \
  --dtb-file="$(pwd)/gem5/system/arm/dt/armv7_gem5_v1_1cpu.dtb" \
  --kernel="${outdir}/build/linux-custom/vmlinux" \
  --machine-type='VExpress_GEM5_V1' \
  --root-device='/dev/sda' \
;
