#!/usr/bin/env bash
if [ "$#" -gt 0 ]; then
  brk="-ex 'break $1'"
else
  brk=""
fi
gdb="$(pwd)/buildroot/output/host/usr/bin/arm-linux-gdb"
cd buildroot/output/build/linux-*.*.*/
cmd="$gdb \
  -q \
  -ex 'add-auto-load-safe-path $(pwd)' \
  -ex 'file vmlinux' \
  -ex 'target remote localhost:1234' \
  -ex 'lx-symbols ../kernel_module-1.0/'
"
#-ex 'set arch i386:x86-64:intel' \
eval "$cmd"
