#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
parsed=$(getopt -o "h${common_getopt_flags}" -l "$common_getopt_flags_long" -- "$@")
eval set -- "$parsed"
while true; do
  case "$1" in
    h)
      echo "https://github.com/cirosantilli/linux-kernel-module-cheat#runtc" 2>&1
      exit
      ;;
    *)
      common_getopt_case "$@"
      ;;
  esac
done
tool="$1"
shift
common_setup
"${common_buildroot_out_dir}/host/bin/"*-buildroot-*"${tool}" "$@"
exit "$?"
