#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
while getopts "h${common_getopts_flags}" OPT; do
  case "$OPT" in
    h)
      echo "https://github.com/cirosantilli/linux-kernel-module-cheat#runtc" 2>&1
      exit
      ;;
    ?)
      common_getopts_case "$OPT"
      ;;
  esac
done
shift "$(($OPTIND - 1))"
tool="$1"
shift
common_setup
"${common_buildroot_out_dir}/host/bin/"*-buildroot-*"${tool}" "$@"
exit "$?"
