#!/usr/bin/env bash
# Maintain different buildroot/output archs with symlinks.
if [ "$#" -ne 1 ]; then
  exit 1
fi
arch="$1"
dst="output.${arch}~"
src='buildroot/output'
mkdir -p "buildroot/$dst"
ln -fns "$dst" "$src"
