#!/usr/bin/env bash
# Minimum requirements to run ./build --download-dependencies
set -ex
if [ $# -eq 1 ]; then
  y=-y
else
  y=
fi
if [ -f /.dockerenv ]; then
  sudo=
  export DEBIAN_FRONTEND=noninteractive
else
  sudo=sudo
fi
$sudo apt-get update
if [ -f /.dockerenv ]; then
  apt install -y software-properties-common
  add-apt-repository -y ppa:git-core/ppa
  $sudo apt update
  git='git=1:2.*'
else
  git=git
fi
$sudo apt-get install $y \
  $git \
  python3 \
  python3-pip \
  python3-distutils \
;
python3 -m pip install --user -r requirements.txt
