#!/usr/bin/env bash
# Minimum requirements to run ./build --download-dependencies
set -ex
if [ $# -eq 1 ]; then
  y=-y
else
  y=
fi
indocker="$(set +e; grep -q docker /proc/1/cgroup; echo $?)"
if [ "$indocker" -eq 0 ]; then
  sudo=
  export DEBIAN_FRONTEND=noninteractive
else
  sudo=sudo
fi
if [ "$indocker" -eq 0 ]; then
  $sudo apt update
  apt install -y software-properties-common
  add-apt-repository -y ppa:git-core/ppa
  $sudo apt update
  git='git=1:2.*'
else
  git=git
fi
$sudo apt-get install $y \
  $git \
  python3 \
  python3-pip \
;
python3 -m pip install -r requirements.txt
