#!/usr/bin/env python3

import common

test_user_mode = common.import_path_relative_root('test-user-mode')

class Main(test_user_mode.Main):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults={
                'emulators': ['native'],
                'in_tree': True,
                'tests': ['.'],
            }
        )

if __name__ == '__main__':
    Main().cli()
