#!/usr/bin/env bash
set -eu
test_size=1
while [ $# -gt 0 ]; do
  case "$1" in
    --size)
      test_size="$2"
      shift 2
      ;;
  esac
done
./bench-boot --size "$test_size"
./test-modules --all-archs --all-emulators
./test-gdb --all-archs --all-emulators
./test-baremetal --all-archs --all-emulators
./test-user-mode --all-archs --all-emulators
