#!/usr/bin/env python3

import os
import sys

import common

class Main(common.TestCliFunction):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#test-userland-in-full-system
'''
        )
    def timed_main(self):
        run = common.import_path_main('run')
        run_args = self.get_common_args()
        run_args['eval_after'] = './test_all.sh;{};'.format(self.env['userland_quit_cmd'])
        self.run_test(run, run_args)

if __name__ == '__main__':
    Main().cli()
