#!/usr/bin/env python3

import imp
import os
import subprocess

git_root = subprocess.check_output([
    'git',
    'rev-parse',
    '--show-toplevel',
]).decode().rstrip()
test_user_mode = imp.load_source(
    'test_user_mode',
    os.path.join(git_root, 'test-user-mode')
)

class Main(test_user_mode.Main):
    def __init__(self):
        super().__init__(
            description='''\
https://github.com/cirosantilli/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults={
                'emulators': ['native'],
                'in_tree': True,
                'tests': ['.'],
            }
        )

if __name__ == '__main__':
    Main().cli()
