#!/usr/bin/env python3

import lkmc.import_path

test_user_mode = lkmc.import_path.import_path_relative_root('test-executables')

class Main(test_user_mode.Main):
    def __init__(self):
        super().__init__(
            description='''\
https://cirosantilli.com/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults={
                'emulators': ['native'],
                'in_tree': True,
                'tests': ['.'],
            }
        )

if __name__ == '__main__':
    Main().cli()
