#!/usr/bin/env bash

set -eux

./build-userland
./build-userland --clean
./build-userland c
./build-userland --clean
./build-userland userland/c
./build-userland --clean
./build-userland userland/c/hello
./build-userland --clean
./build-userland userland/c/hello.c
./build-userland --clean
./build-userland userland/c/hello.out
./build-userland --clean

./build-userland --in-tree
./build-userland --in-tree --clean
./build-userland --in-tree c
./build-userland --in-tree --clean
./build-userland --in-tree userland/c
./build-userland --in-tree --clean
./build-userland --in-tree userland/c/hello
./build-userland --in-tree --clean
./build-userland --in-tree userland/c/hello.c
./build-userland --in-tree --clean
./build-userland --in-tree userland/c/hello.out
./build-userland --in-tree --clean

cd userland

./build-userland --in-tree
./build-userland --in-tree --clean
./build-userland --in-tree c
./build-userland --in-tree --clean
./build-userland --in-tree c/hello
./build-userland --in-tree --clean
./build-userland --in-tree c/hello.c
./build-userland --in-tree --clean
./build-userland --in-tree c/hello.out
./build-userland --in-tree --clean
