#!/usr/bin/env bash

# Quick sanity check that userland target resoltion at least does not blow up.

set -eux

./build-userland
./build-userland --clean
./build-userland userland/c
./build-userland --clean userland/c
./build-userland userland/c/hello
./build-userland --clean userland/c/hello
./build-userland userland/c/hello.
./build-userland --clean userland/c/hello.
./build-userland userland/c/hello.c
./build-userland --clean userland/c/hello.c
./build-userland userland/c/hello.out
./build-userland --clean userland/c/hello.out
./build-userland "$(pwd)/userland/c/hello.out"
./build-userland --clean "$(pwd)/userland/c/hello.out"

./build-userland --in-tree
./build-userland --in-tree --clean
./build-userland --in-tree userland/c
./build-userland --in-tree --clean userland/c
./build-userland --in-tree userland/c/hello
./build-userland --in-tree --clean userland/c/hello
./build-userland --in-tree userland/c/hello.
./build-userland --in-tree --clean userland/c/hello.
./build-userland --in-tree userland/c/hello.c
./build-userland --in-tree --clean userland/c/hello.c
./build-userland --in-tree userland/c/hello.out
./build-userland --in-tree --clean userland/c/hello.out
./build-userland --in-tree "$(pwd)/userland/c/hello.out"
./build-userland --in-tree --clean "$(pwd)/userland/c/hello.out"
./build-userland --in-tree --clean

cd userland
./build
./build --clean
./build c
./build --clean c
./build c/hello
./build --clean c/hello
./build c/hello.
./build --clean c/hello.
./build c/hello.c
./build --clean c/hello.c
./build c/hello.out
./build --clean c/hello.out
./build "$(pwd)/c/hello.out"
./build --clean "$(pwd)/c/hello.out"
