#!/usr/bin/env python3

import lkmc.import_path

test_user_mode = lkmc.import_path.import_path_relative_root('test-executables')

class Main(test_user_mode.Main):
    def __init__(self):
        defaults = {
            'emulators': ['native'],
            'in_tree': True,
            'tests': ['.'],
        }
        if self.cwd_in_lib():
            defaults['package_all'] = True
        super().__init__(
            description='''\
https://cirosantilli.com/linux-kernel-module-cheat#userland-setup-getting-started-natively
''',
            defaults=defaults
        )

if __name__ == '__main__':
    Main().cli()
