#!/usr/bin/env bash
set -eu
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
getvar="${root_dir}/getvar"
termout_file="$("$getvar" termout_file)"
./run --eval-busybox '/test_all.sh;/poweroff.out' --kvm
grep -q lkmc_test_pass "$termout_file"
