#!/usr/bin/env bash
# TODO: move to Python.
if [ "$(tmux list-panes | wc -l | cut -d' ' -f1)" -ne 1 ]; then
  tmux kill-pane -t 1
fi
# https://unix.stackexchange.com/questions/439031/how-to-split-the-window-that-ran-the-tmux-split-window-command-instead-of-the/439032#439032
tmux split-window -dh -t "$TMUX_PANE" "bash --rcfile <(echo '. ~/.bashrc;$*')"
