#!/usr/bin/env python3

import common
from shell_helpers import LF

class Main(common.LkmcCliFunction):
    def __init__(self):
        super().__init__(
            description='''Trace the PIC addresses executed on a Linux kernel boot.

More information at: https://github.com/cirosantilli/linux-kernel-module-cheat#tracing
'''
        )

    def timed_main(self):
        args = self.get_common_args()
        run = self.import_path_main('run')
        self.common_args['kernel_cli'] = self.env['quit_init']
        if self.env['emulator'] == 'gem5':
            args['trace'] = 'Exec,-ExecSymbol,-ExecMicro'
            run.main(**args)
        elif self.env['emulator'] == 'qemu':
            run_args = args.copy()
            args['trace'] = 'exec_tb'
            run.main(**run_args)
            qemu_trace2txt = self.import_path_main('qemu-trace2txt')
            qemu_trace2txt.main(**args)
            # Instruction count.
            # We could put this on a separate script, but it just adds more arch boilerplate to a new script.
            # So let's just leave it here for now since it did not add a significant processing time.
            kernel_entry_addr = hex(self.get_elf_entry(self.env['vmlinux']))
            nlines = 0
            nlines_firmware = 0
            with open(self.env['qemu_trace_txt_file'], 'r') as trace_file:
                in_firmware = True
                for line in trace_file:
                    line = line.rstrip()
                    nlines += 1
                    pc = line.split('=')[-1]
                    if pc == kernel_entry_addr:
                        in_firmware = False
                    if in_firmware:
                        nlines_firmware += 1
            print('''\
instructions {}
entry_address {}
instructions_firmware {}
'''.format(
                    nlines,
                    kernel_entry_addr,
                    nlines_firmware
                ),
                end=''
            )

if __name__ == '__main__':
    Main().cli()
