#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
common_setup
outfile="${common_out_dir}/lkmc-${common_sha}.zip"
rm -f "$outfile"
for arch in x86_64 arm aarch64; do
  common_setup
  rm -f "${common_images_dir}/rootfs.ext2"
  zip -r "$outfile" "$common_images_dir"
done
