#!/usr/bin/env bash
set -eu
# Ideally should be obtained from common.
# But the paths there are absolute, and get recorded by in zip.
# and generating relative paths seems hard:
# https://stackoverflow.com/questions/2564634/convert-absolute-path-into-relative-path-given-a-current-directory-using-bash
sha="$(git log -1 --format="%H")"
for arch in x86_64 arm aarch64; do
  img_dir="out/${arch}/buildroot/images"
  rm -f "${img_dir}/rootfs.ext2"
  zip -r "out/images-${sha}.zip" "${img_dir}"
done
