#!/bin/sh
# https://github.com/cirosantilli/linux-kernel-module-cheat#init-busybox
echo "hello S98"
cd "$lkmc_home"
if [ -n "$lkmc_eval" ]; then
  eval "$lkmc_eval"
elif [ -n "$lkmc_eval_base64" ]; then
  eval "$(printf "$lkmc_eval_base64" | base64 -d)"
fi
exit 0
