#!/usr/bin/env bash
set -eux

# myfile_user works from all directories.
./myfile_user.py
cd ..
relative_import/myfile_user.py
cd relative_import/mydir
../myfile_user.py
cd ..

# TODO any better way to run mydir/myfile_user.py?

# ./mydir/myfile_user.py
#Traceback (most recent call last):
#  File "./mydir/myfile_user.py", line 3, in <module>
#    import myfile
#ModuleNotFoundError: No module named 'myfile'

python -m mydir.myfile_user
